version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"  # expose nginx sur le port 80 de ta machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Charge la config nginx depuis le fichier local
    depends_on:
      - beef  # Assure que BeEF est déjà lancé avant nginx (si nécessaire)
    networks:
      - beef_network  # Le même réseau Docker que BeEF

networks:
  beef_network:
    external: true  # Utilise le réseau externe Docker (ou crée un nouveau réseau)
